# Generated by Django 5.0.6 on 2024-08-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_column_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
