# Generated by Django 5.0.6 on 2024-08-15 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_data_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='content',
        ),
    ]
