# Generated by Django 5.0.6 on 2024-08-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_row_data_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='data_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean')], max_length=50),
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
