# Generated by Django 5.0.6 on 2024-08-15 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_alter_column_data_type_delete_fileupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='data_type',
        ),
    ]
