# Generated by Django 5.1 on 2024-08-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_table_description_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
