# Generated by Django 5.1 on 2024-08-18 04:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_projectshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='shared_users',
            field=models.ManyToManyField(blank=True, related_name='shared_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ProjectShare',
        ),
    ]
