# Generated by Django 5.1 on 2024-08-20 04:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_customuser_is_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='shared_users',
            field=models.ManyToManyField(blank=True, default=False, related_name='shared_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
