# Generated by Django 5.1 on 2024-08-22 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_table_created_at_table_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='apps.project'),
        ),
    ]
